spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 2KB
      max-request-size: 500MB
  config:
    activate:
      on-profile:
        dev
  datasource:
    url: jdbc:mysql://localhost:3308/metaclassroom
    username: root
    password: 1234
  #    url: jdbc:mysql://tkd.vrware.us:3306/tkd-dev
  #    username: globepoint
  #    password: globepoint
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 200
        format_sql: true
        use_sql_comments: true

#로그
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    com.metaclassroom : DEBUG
#swagger api 문서
springdoc:
  swagger-ui:
    groups-order: desc
    operations-sorter: method
    path: /swagger-ui.html
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8