config:
  activate:
    on-profile: prod
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      default_batch_fetch_size: 100
      format_sql: true

server:
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    operations-sorter: alpha
